/*
 * 全局指标 ID，统一收口账户、分析、图表和悬浮窗允许消费的正式指标名称。
 */
package com.binance.monitor.ui.rules;

public enum IndicatorId {
    ACCOUNT_TOTAL_ASSET,
    ACCOUNT_NET_ASSET,
    ACCOUNT_AVAILABLE_FUNDS,
    ACCOUNT_MARGIN,
    ACCOUNT_POSITION_PNL,
    ACCOUNT_POSITION_PNL_RATE,
    ACCOUNT_TOTAL_RETURN_AMOUNT,
    ACCOUNT_TOTAL_RETURN_RATE,
    ACCOUNT_MAX_DRAWDOWN,
    ACCOUNT_SHARPE_RATIO,
    TRADE_TOTAL_COUNT,
    TRADE_WIN_RATE,
    TRADE_AVG_PROFIT,
    TRADE_AVG_LOSS,
    TRADE_WIN_LOSS_COUNT,
    TRADE_GROSS_PROFIT_LOSS
}
